### ISSUE TITLE
annotion

### ISSUE THREAD

**Issue by shunshizhechang** [CryFeiFei/Reader#1]
添加一个annotion，鼠标如何才能交互呢？

**Comment by CryFeiFei** [comment]
界面层传入坐标-> kit层 hint到注释然后反应到页面上->修改界面层逻辑->最后再保存到kit层,这块还没写，接下来的大部分工作是注释部分

**Comment by shunshizhechang** [comment]
Poppler中有Poppler::LinkAction，annotion中也有AdditionalActionType的介绍，这些只是给搭建的框架吗，其实现的接口要自己去写吗？正如你说的“ kit层 hint到注释然后反应到页面上”，这个过程中Poppler没有留下接口吗？

**Comment by CryFeiFei** [comment]
不用自己写啊，poppler都已经写好了啊，应用层的显示得自己来做，那个试试写到kit层

**Comment by CryFeiFei** [comment]
我觉得你的问题是现在没有分清楚哪些是应用层该做的，哪些是poppler该做的
