### ISSUE TITLE
不能正常显示电子发票类的PDF文件

### ISSUE THREAD

**Issue by kimkata** [CryFeiFei/Reader#4]
我想制作一个批量打印电子发票的程序，于是fork了你的代码，自己修改了一个，等要修改完，才发现poppler无法正常显示电子发票类的PDF，不知道是不是这个版本的dll文件不支持。我又试了一下mupdf，完美显示。

**Comment by CryFeiFei** [comment]
能说下平台么？方便把样张发上来么

**Comment by kimkata** [comment]
[加油电子发票.pdf](https://github.com/CryFeiFei/Reader/files/2153760/default.pdf)
[京东商城电子发票.pdf](https://github.com/CryFeiFei/Reader/files/2153761/default.pdf)
你好，这2个都是电子发票,问题是其中的一些内容不能显示，应该是render渲染的问题。我的平台是：windows 10，qt 5.9 MinGW

**Comment by CryFeiFei** [comment]
好的，晚上下班我试一下～谢谢使用。
既然mupdf没有问题，我觉得你可以用Qt简单的封装下mupdf的接口，我的阅读器还算是分的比较详细的。你可以重新实现下kit层。

**Comment by kimkata** [comment]
好的，你可以试试poppler 0.66的版本有没有问题，目前在网上好像只提供了0.39版本的Windows上可使用的qt dll文件， 我尝试在windows下编译0.66，没编译成功。
mupdf的网上有提供qt编译版本，但是这个项目已经几年没有更新了，使用的是visual studio 2013才能使用，换msvc 2017的编译器,没编译成功。
如果你这个项目poppler能够完美地渲染，那就太好了。

**Comment by CryFeiFei** [comment]
我现在手里只有ubuntu14.04显示发票这样，你看看正常么？
![reader](https://user-images.githubusercontent.com/16486417/42155465-0ee83c44-7e1b-11e8-8b7c-aecb85e18e07.png)

**Comment by kimkata** [comment]
![2](https://user-images.githubusercontent.com/20291320/42160684-bb791d16-7e2a-11e8-8c30-eb19cdfb782d.jpg)
您这是正常的，非常好，不知道是不是因为我的windows 10下字库不全？

**Comment by CryFeiFei** [comment]
应该不是字体库不全，应该是这个版本的dll不是最新的。找个时间，我重新编译一下看看吧。windows的dll也是我从网上下载的，没有重新编译。希望给我个fork跟star，比心

**Comment by kimkata** [comment]
好的。

**Comment by kimkata** [comment]
我加了poppler-data,就好了。就是字库的问题。

**Comment by CryFeiFei** [comment]
你说在pro文件中加上么？还是编译参数，希望你给我提个request
