### ISSUE TITLE
link to poppler library

### ISSUE THREAD

**Issue by ChengHuangUCAS** [CryFeiFei/Reader#6]
Hello, I tried to build this project on win10 with Qt 5.10. It complains '  error: LNK1104: 无法打开文件“libpoppler.lib” '. It seems that the way you link to poppler library 

> win32: LIBS += -L$$PWD/3rdparty/Win32/Poppler -llibpoppler

> win32: LIBS += -L$$PWD/3rdparty/Win32/Poppler -llibpoppler-qt5

 is expecting *.lib file rather than *.dll. So how can I build this correctly on windows?

**Comment by CryFeiFei** [comment]
hi,the poppler build by mingw ,what is your compiler？

**Comment by ChengHuangUCAS** [comment]
Ah, I see. My compiler is MSVC2017 64bit. I changed it to mingw and it worked. Thank you very much!
And I wonder what's the difference between them besides 64-bit and 32-bit?

**Comment by CryFeiFei** [comment]
i suggest you compile the commit 1592cd4546bf35d3ce3bfbd500c7f6ea51255ea0。because， the last commit are not work well，and，I am going to rewrite my frame。and are you chinese？

**Comment by ChengHuangUCAS** [comment]
是的哈哈哈哈，我只是觉得如果别人也遇到这个问题就都可以看懂了。。。还想请问一下你是怎么解决poppler那些依赖的。项目经验太少了，感觉很棘手啊。

**Comment by CryFeiFei** [comment]
这个就是按照官网一点点来的，你只是嫌麻烦吧哈哈哈，你可以下载那个最后一次提交的上一条记录来看，我最近在重构架构

**Comment by ChengHuangUCAS** [comment]
按官网上下载了源码，然后按照里面INSTALL那个文件说的做，可是cmake的时候就说需要freetype，jpeg等等各种。我就是不太懂这些东西要怎么弄。。。

**Comment by CryFeiFei** [comment]
是的，因为需要绘制字体啥的，其实Qt也需要，不过是都给你打包好了，觉得我的Reader可以的话，给我个star吧

**Comment by ChengHuangUCAS** [comment]
已经给了。这个是我最近找了类似的解决方案里唯一能通过编译的。。。不过我们需要的是一个类似poppler或者pdfium的Qt库，可是没法搞定，还是得继续折腾唉

**Comment by CryFeiFei** [comment]
哈哈哈哈，我可不是那些乱七八糟的水货。pdfuim编译也挺蛋疼的。不过最近很忙。没时间去编译
